project:
  type: website
  output-dir: docs

website:
  title: "mjswelise"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datastory.qmd
        text: Data Story
      - href: subsfolders.qmd
        text: Past Submissions
    right:
      - href: courses.qmd
        text: Past Modules
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: lux
      dark: quartz
    css: styles.css
    toc: true

editor: visual