---
title: "Elise Wong"
about:
  template: trestles
  image: https://media.licdn.com/dms/image/D5603AQGqmBZvYZYA8g/profile-displayphoto-shrink_400_400/0/1669535005905?e=1703116800&v=beta&t=zfAbizJlSE7yjcbaXO5Z6M7-nxd8uUVJwDR8h_dGxms
  image-width: 10em
  image-shape: round
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/mjswelise
    - icon: github
      text: Github
      href: https://github.com/mjswelise
---

# Who?

<b>Elise Wong</b> is currently a sophomore at the National University of Singapore (NUS), pursuing her undergraduate degree in Communications and New Media with a Second Major in Sociology.

# What?

Elise's active engagement in the arts, especially her passion for music, serves as a living testament to how communication transcends mere words and text - as an active member and one of the leaders of Raffles Hall's rock band, RHockerfellas, Elise rocks the stage with her electric guitar skills, playing to her various audiences, reinforcing the idea that music itself is a powerful form of communication.

# Why?

This affinity for music has also guided her choice of dataset for her Data Story Final Project. Given her background and profound interest in music, she decided to work with [Spotify statistics](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md). By analysing Spotify data, she can combine her academic knowledge with her passion for music, creating a project that resonates with her on a personal level.

In all, Elise believes that this synergy between her passion and the chosen dataset will enable her to produce a project that is not only academically rigorous but also emotionally fulfilling.

<i>This website was developed as part of the <b>Data Story Final Project</b> for the <b>NM2207 ('Computational Media Literacy')</b> course, during AY23/24 Semester 1.</i>
