<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mjswelise - How Does Genre Classification Work? A Study of Spotify Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">mjswelise</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./datastory.html" aria-current="page">
 <span class="menu-text">Data Story</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./subsfolders.html">
 <span class="menu-text">Past Submissions</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./courses.html">
 <span class="menu-text">Past Modules</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#tidying-data" id="toc-tidying-data" class="nav-link" data-scroll-target="#tidying-data">‘Tidying’ Data</a></li>
  <li><a href="#defining-genre" id="toc-defining-genre" class="nav-link" data-scroll-target="#defining-genre">Defining Genre</a>
  <ul class="collapse">
  <li><a href="#so-lets-try-to-classify-genres" id="toc-so-lets-try-to-classify-genres" class="nav-link" data-scroll-target="#so-lets-try-to-classify-genres">So, Let’s Try to Classify Genres?</a></li>
  </ul></li>
  <li><a href="#test-the-predictive-algorithm" id="toc-test-the-predictive-algorithm" class="nav-link" data-scroll-target="#test-the-predictive-algorithm">Test the Predictive Algorithm</a></li>
  <li><a href="#discussion-and-conclusion" id="toc-discussion-and-conclusion" class="nav-link" data-scroll-target="#discussion-and-conclusion">Discussion and Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">How Does Genre Classification Work? A Study of Spotify Data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p><strong>“Music expresses that which cannot be put into words and that which cannot remain silent</strong>.” - Victor Hugo</p>
</blockquote>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In delving into the mechanics of genre classification within the realm of music, this study takes a comprehensive look at the inner workings of Spotify’s genre classification system. Extending its scope across six decades, from 1957 to 2020, this musical exploration serves as a time-traveling odyssey, unraveling the intricate threads that define how music genres not only mold themselves but are intricately woven into the fabric of shifting industry dynamics and evolving listener preferences.</p>
<p>The significance of this exploration is heightened amidst the rapidly transforming landscape of the music industry. As indicated by the Recording Industry Association of America (2022), the surge in revenues from streaming music has been remarkable, constituting an astonishing 84% of total music revenues in the initial half of 2021. At the forefront of this revolution stands Spotify, acknowledged as the “world’s largest music streaming provider in terms of global paid-for subscriptions” (Music Business Worldwide, 2023), with projections foreseeing sustained dominance throughout the 2020s (Goldman Sachs, 2023). Simultaneously, the advent of digital music platforms has led to a departure from rigid “hard genre categorisation” to a more adaptable “mood-based categorisation” approach. This strategic shift aims at fostering new music through effective exposure, as highlighted by industry observers (The Guardian, 2017).</p>
<p>Thus, scrutinising the metamorphosis of music genre categorization on Spotify in response to released songs transcends mere academic inquiry. It serves as a focal point through which we can glean insights into the dynamic interplay of change and continuity within the music industry. This understanding not only informs business strategies but also provides valuable perspectives on the perpetually evolving musical landscape, particularly within the context of our increasingly digitised society.</p>
</section>
<section id="tidying-data" class="level2">
<h2 class="anchored" data-anchor-id="tidying-data">‘Tidying’ Data</h2>
<div class="cell">

</div>
<p>First, to isolate the tracks, genres, and audio features for easy processing, I created a new data-set with the relevant variables. I also created a list of genres and the respective quantity of songs for each.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> playlist_genre </th>
   <th style="text-align:right;"> n </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> edm </td>
   <td style="text-align:right;"> 6043 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> latin </td>
   <td style="text-align:right;"> 5155 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> pop </td>
   <td style="text-align:right;"> 5507 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> r&amp;b </td>
   <td style="text-align:right;"> 5431 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rap </td>
   <td style="text-align:right;"> 5746 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rock </td>
   <td style="text-align:right;"> 4951 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Using ggplot, to get a sensing of the dataset, I then plot the data into graphs to find the overall trends in genre popularity, subgenre dynamics, and the counts of each subgenre within each genre.</p>
<p>Find it in my interactive Shiny app below!</p>
<p>&lt;iframe height=“400” width=“100%” frameborder=“no” src=“https://mjswelise.shinyapps.io/2207dataset_overview/”&gt; &lt;/iframe&gt;</p>
</section>
<section id="defining-genre" class="level2">
<h2 class="anchored" data-anchor-id="defining-genre">Defining Genre</h2>
<p>In my quest to determine what makes a ‘genre’, I first condensed the data-sets ‘by year’ from YYYY-MM-DD. Here, I found that there was an insufficient population size of songs from before 1966 (i.e.&nbsp;&lt;30 instances), and chose to filter the data that way to ensure a more accurate output from my dataset.</p>
<div class="cell">

</div>
<section id="density-of-audio-features-by-genre" class="level4">
<h4 class="anchored" data-anchor-id="density-of-audio-features-by-genre">Density of Audio Features by Genre</h4>
<p>Then, I created a histogram to determine the density of audio features by genre. Here, we can observe that, collectively, the songs in the dataset lean towards characteristics such as low acousticness, liveness, instrumentalness, and speechiness, coupled with higher danceability, energy, and loudness.</p>
<p>On a genre-specific level, EDM tends to feature lower acoustic elements, heightened energy, and subdued valence, conveying a sense of melancholy. In contrast, Latin music is characterised by elevated valence, indicating a positive and cheerful mood, along with pronounced danceability. Rap songs stand out for their high speechiness and danceability, while rock compositions favor live recordings and exhibit lower danceability.</p>
<p>Examining song durations by genre reveals that Pop, Latin, and EDM songs tend to be shorter, while R&amp;B, rap, and rock songs are associated with longer durations.</p>
<p>Analysis of the histogram suggests that elements like energy, valence, tempo, and danceability hold significant potential for distinguishing between genres, whereas instrumentalness and key may contribute less prominently to genre classification.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># density of audio features by genre, probably change this to shiny</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>audio_features <span class="ot">&lt;-</span> <span class="fu">names</span>(spotify_songs)[<span class="fu">c</span>(<span class="dv">12</span><span class="sc">:</span><span class="dv">23</span>)]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>spotify_songs <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">'playlist_genre'</span>, audio_features)) <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> audio_features) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> playlist_genre), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">ncol =</span> <span class="dv">4</span>, <span class="at">scales =</span> <span class="st">'free'</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Histogram - Audio Features by Genre'</span>, <span class="at">y =</span> <span class="st">'Density'</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="datastory_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="768"></p>
</div>
</div>
</section>
<section id="correlation-between-individual-audio-features" class="level4">
<h4 class="anchored" data-anchor-id="correlation-between-individual-audio-features">Correlation between Individual Audio Features</h4>
<p>In addition, I found the correlation between individual audio features, as well as of individual genres (in the next section!). I wanted to evaluate any further interdependencies among these musical characteristics, as well as to understand the correlation patterns specific to distinct genres, to shed light on how the musical attributes within each genre are interconnected.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation between audio features</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>spotify_songs <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(audio_features) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="at">method =</span> <span class="st">'color'</span>, </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="st">'hclust'</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type =</span> <span class="st">'lower'</span>, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">diag =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">col =</span> <span class="fu">COL2</span>(<span class="st">'PuOr'</span>, <span class="dv">100</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tl.col =</span> <span class="st">'black'</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">number.cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">title =</span> <span class="st">'Correlation between Audio Features'</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cex.main =</span> <span class="fl">0.8</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tl.cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cl.ratio =</span> <span class="fl">0.2</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cl.cex =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="datastory_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>Across the audio features, energy and loudness seem especially correlated, with a score of +0.68. As such, perhaps, here, we can establish that loudness is less relevant in a genre classification sense, given that energy is still strongly associated with having distinctions with other audio features (i.e.&nbsp;negatively correlated with acousticness, at -0.54, which can be used as a differentiating factor).</p>
<p>Other noticeable correlations can include danceability and valence, which are positively correlated at +0.33.</p>
</section>
<section id="correlation-between-individual-genres" class="level4">
<h4 class="anchored" data-anchor-id="correlation-between-individual-genres">Correlation between Individual Genres</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation between genres</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>genre_median <span class="ot">&lt;-</span> spotify_songs <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(playlist_genre) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, median, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>genre_overview <span class="ot">&lt;-</span> genre_median <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(audio_features, <span class="sc">-</span>mode) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(genre_overview) <span class="ot">&lt;-</span> genre_median<span class="sc">$</span>playlist_genre</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(genre_overview) <span class="ot">&lt;-</span> genre_median<span class="sc">$</span>playlist_genre</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>genre_overview <span class="sc">%&gt;%</span> corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="at">method =</span> <span class="st">'color'</span>, </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="st">'hclust'</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type =</span> <span class="st">'lower'</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tl.col =</span> <span class="st">'black'</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">diag =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>                     <span class="at">col =</span> <span class="fu">COL2</span>(<span class="st">'PuOr'</span>, <span class="dv">100</span>),</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>                     <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>                     <span class="at">number.cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>                     <span class="at">title =</span> <span class="st">'Correlation between Genre Features'</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cex.main =</span> <span class="fl">0.8</span>,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>),</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tl.cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cl.ratio =</span> <span class="fl">0.2</span>,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">cl.cex =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="datastory_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>Statistically, by genre, R&amp;B and EDM are most different from each other - they are strongly and negatively correlated by -0.77. In terms of similarities, Latin and R&amp;B seem most similar, positively correlated by 0.45.</p>
</section>
<section id="so-lets-try-to-classify-genres" class="level3">
<h3 class="anchored" data-anchor-id="so-lets-try-to-classify-genres">So, Let’s Try to Classify Genres?</h3>
<p>In light of this information, the analysis has provided valuable insights into the characteristics that define each genre. Now, the focus shifts towards creating a quantifiable method for genre categorisation.</p>
<p>To achieve this, I planned to identify the median value of each audio feature for each genre and compare it with the overall median of the entire dataset. The exploration of median values for each genre’s audio features in comparison to the overall dataset median will serve as a quantitative basis for discerning the distinctive attributes that define each genre.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> pop </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 52 </td>
   <td style="text-align:left;"> -7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.653 </td>
   <td style="text-align:left;"> 0.021 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.724 </td>
   <td style="text-align:left;"> -0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.0495 </td>
   <td style="text-align:left;"> 0.0141 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.0810 </td>
   <td style="text-align:left;"> 0.0791 </td>
   <td style="text-align:left;"> 0.0019 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 9.86e-06 </td>
   <td style="text-align:left;"> 5.44e-06 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.123 </td>
   <td style="text-align:left;"> 0.004 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.498 </td>
   <td style="text-align:left;"> 0.00800000000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.001 </td>
   <td style="text-align:left;"> 120.004 </td>
   <td style="text-align:left;"> 1.997 </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> r&amp;b </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.689 </td>
   <td style="text-align:left;"> -0.0149999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.594 </td>
   <td style="text-align:left;"> 0.127 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.0692 </td>
   <td style="text-align:left;"> -0.00559999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.0810 </td>
   <td style="text-align:left;"> 0.1695 </td>
   <td style="text-align:left;"> -0.0885 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 4.19e-06 </td>
   <td style="text-align:left;"> 1.111e-05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.120 </td>
   <td style="text-align:left;"> 0.00700000000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.533 </td>
   <td style="text-align:left;"> -0.027 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.0010 </td>
   <td style="text-align:left;"> 109.0075 </td>
   <td style="text-align:left;"> 12.9935 </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> rap </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 48 </td>
   <td style="text-align:left;"> -3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.737 </td>
   <td style="text-align:left;"> -0.063 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.665 </td>
   <td style="text-align:left;"> 0.0559999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.1740 </td>
   <td style="text-align:left;"> -0.1104 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.081 </td>
   <td style="text-align:left;"> 0.112 </td>
   <td style="text-align:left;"> -0.031 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 0.00e+00 </td>
   <td style="text-align:left;"> 1.53e-05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.509 </td>
   <td style="text-align:left;"> -0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.001 </td>
   <td style="text-align:left;"> 120.058 </td>
   <td style="text-align:left;"> 1.943 </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> edm </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 36 </td>
   <td style="text-align:left;"> 9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.658 </td>
   <td style="text-align:left;"> 0.016 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.831 </td>
   <td style="text-align:left;"> -0.11 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.0602 </td>
   <td style="text-align:left;"> 0.00340000000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.0810 </td>
   <td style="text-align:left;"> 0.0193 </td>
   <td style="text-align:left;"> 0.0617 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 3.95e-03 </td>
   <td style="text-align:left;"> -0.0039347 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.139 </td>
   <td style="text-align:left;"> -0.012 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.368 </td>
   <td style="text-align:left;"> 0.138 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.001 </td>
   <td style="text-align:left;"> 127.040 </td>
   <td style="text-align:left;"> -5.039 </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> rock </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.523 </td>
   <td style="text-align:left;"> 0.151 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.785 </td>
   <td style="text-align:left;"> -0.0640000000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.0427 </td>
   <td style="text-align:left;"> 0.0209 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.0810 </td>
   <td style="text-align:left;"> 0.0327 </td>
   <td style="text-align:left;"> 0.0483 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 2.10e-04 </td>
   <td style="text-align:left;"> -0.0001947 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.138 </td>
   <td style="text-align:left;"> -0.011 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.521 </td>
   <td style="text-align:left;"> -0.015 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.001 </td>
   <td style="text-align:left;"> 124.166 </td>
   <td style="text-align:left;"> -2.16499999999999 </td>
  </tr>
</tbody>
</table>

</div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> medians </th>
   <th style="text-align:left;"> latin </th>
   <th style="text-align:left;"> subtracted_value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> track_popularity </td>
   <td style="text-align:left;"> 45 </td>
   <td style="text-align:left;"> 51 </td>
   <td style="text-align:left;"> -6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> danceability </td>
   <td style="text-align:left;"> 0.674 </td>
   <td style="text-align:left;"> 0.729 </td>
   <td style="text-align:left;"> -0.0549999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> energy </td>
   <td style="text-align:left;"> 0.721 </td>
   <td style="text-align:left;"> 0.728 </td>
   <td style="text-align:left;"> -0.00700000000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> key </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> speechiness </td>
   <td style="text-align:left;"> 0.0636 </td>
   <td style="text-align:left;"> 0.0681 </td>
   <td style="text-align:left;"> -0.00449999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> acousticness </td>
   <td style="text-align:left;"> 0.081 </td>
   <td style="text-align:left;"> 0.139 </td>
   <td style="text-align:left;"> -0.058 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instrumentalness </td>
   <td style="text-align:left;"> 1.53e-05 </td>
   <td style="text-align:left;"> 2.43e-06 </td>
   <td style="text-align:left;"> 1.287e-05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> liveness </td>
   <td style="text-align:left;"> 0.127 </td>
   <td style="text-align:left;"> 0.121 </td>
   <td style="text-align:left;"> 0.006 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> valence </td>
   <td style="text-align:left;"> 0.506 </td>
   <td style="text-align:left;"> 0.624 </td>
   <td style="text-align:left;"> -0.118 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tempo </td>
   <td style="text-align:left;"> 122.001 </td>
   <td style="text-align:left;"> 110.452 </td>
   <td style="text-align:left;"> 11.549 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>As such, the preliminary defining variables for each genre are:</p>
<p>‘Pop’ - popularity, energy</p>
<p>‘R&amp;B’ - danceability, speechiness, acousticness, valence</p>
<p>‘Rap’ - popularity, danceability, speechiness, acousticness, valence</p>
<p>‘EDM’ - energy, instrumentalness, liveness, tempo</p>
<p>‘Rock’ - energy, instrumentalness, liveness, valence, tempo</p>
<p>‘Latin’ - energy, instrumentalness, liveness, valence, tempo</p>
</section>
</section>
<section id="test-the-predictive-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="test-the-predictive-algorithm">Test the Predictive Algorithm</h2>
<p>In the pursuit of evaluating the effectiveness of my predictive algorithm (i.e.&nbsp;of using audio features to predict genre), the decision was made to employ decision trees as the analytical framework. Decision trees, renowned for their interpretability and efficiency in handling classification tasks, were selected to discern the feasibility of classifying music genres based on the prominence of audio features.</p>
<p>The utilisation of decision trees aligns with the objective of unveiling discernible patterns within the intricate interplay of audio features, providing valuable insights into the distinctive characteristics that define various musical genres. This section undertakes the crucial task of testing the predictive capabilities of the algorithm, shedding light on its potential to accurately classify genres based on the nuanced nuances of audio feature prominence.</p>
<p>Here, the decision tree was structured as such:</p>
<ol type="1">
<li><p><strong>Energy Check:</strong> If the energy level of the song is greater than 0.721, the function classifies it as “pop.” This suggests that songs with high energy levels are predominantly associated with the pop genre.</p></li>
<li><p><strong>Popularity and Danceability Check:</strong> If the song’s track popularity exceeds 45, a secondary check is initiated. If the danceability of the song surpasses 0.674, it is categorized as “latin.” Otherwise, it is classified as “pop.” This implies that highly popular songs with elevated danceability are likely to fall into the Latin genre.</p></li>
<li><p><strong>Danceability Check:</strong> If the danceability of the song is greater than 0.674 (but the popularity condition is not met), it is labeled as “r&amp;b.” This indicates that songs with high danceability but not necessarily high popularity are inclined towards the R&amp;B genre.</p></li>
<li><p><strong>Valence Check:</strong> If the valence (positivity) of the song exceeds 0.506 (but neither the energy nor danceability conditions are met), the function assigns the genre as “rock.” This suggests that songs with a positive emotional tone are associated with the rock genre.</p></li>
<li><p><strong>Default Case:</strong> If none of the above conditions are met, the function defaults to classifying the song as “edm.” This serves as a catch-all category for songs that do not meet the specific criteria outlined for the other genres.</p></li>
</ol>
<p>Notably, I had initially set the initial default case to classify songs as “pop.” However, recognising the overrepresentation of pop songs within the dataset, the default classification was adjusted to “edm” instead. This modification aims to ensure a more balanced and nuanced approach to genre assignment, considering the diversity of the dataset and avoiding a disproportionate bias toward the pop genre.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>classify_genre <span class="ot">&lt;-</span> <span class="cf">function</span>(song) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (song[<span class="st">"energy"</span>] <span class="sc">&gt;</span> <span class="fl">0.721</span>) {</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"pop"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (song[<span class="st">"track_popularity"</span>] <span class="sc">&gt;</span> <span class="dv">45</span>) {</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (song[<span class="st">"danceability"</span>] <span class="sc">&gt;</span> <span class="fl">0.674</span>) {</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="st">"latin"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="st">"pop"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (song[<span class="st">"danceability"</span>] <span class="sc">&gt;</span> <span class="fl">0.674</span>) {</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"r&amp;b"</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (song[<span class="st">"valence"</span>] <span class="sc">&gt;</span> <span class="fl">0.506</span>) {</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"rock"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"edm"</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>spotify_songs<span class="sc">$</span>predicted_genre <span class="ot">&lt;-</span> <span class="fu">apply</span>(spotify_songs, <span class="dv">1</span>, classify_genre)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> spotify_songs <span class="sc">%&gt;%</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(track_name, track_popularity, track_album_release_date, </span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>         playlist_genre, predicted_genre, danceability, energy, key, </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>         speechiness, acousticness, instrumentalness, liveness, valence, tempo) <span class="sc">%&gt;%</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">match =</span> <span class="fu">if_else</span>(playlist_genre <span class="sc">==</span> predicted_genre, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>))</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>accuracy_predictions <span class="ot">&lt;-</span> predictions <span class="sc">%&gt;%</span> </span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">match =</span> <span class="fu">ifelse</span>(playlist_genre <span class="sc">==</span> predicted_genre, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(match) <span class="sc">%&gt;%</span> </span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">accuracy =</span> n<span class="sc">/</span><span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>accuracy_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  match     n accuracy
1 FALSE 26626 81.09524
2  TRUE  6207 18.90476</code></pre>
</div>
</div>
<p>However, as per the accuracy table above, the percentage accuracy of classification remained to be less than 20%.</p>
<p>To test it again, I tried the predictive algorithm on a smaller test set, instead of the whole data-set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># trying with a test case of 10 random songs from the spotify_songs dataset</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>random_10 <span class="ot">&lt;-</span> spotify_songs <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">10</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>random_10<span class="sc">$</span>predicted_genre <span class="ot">&lt;-</span> <span class="fu">apply</span>(random_10, <span class="dv">1</span>, classify_genre)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>predictions10 <span class="ot">&lt;-</span> random_10 <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(track_name, track_popularity, track_album_release_date, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>         playlist_genre, predicted_genre, danceability, energy, key, </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>         speechiness, acousticness, instrumentalness, liveness, valence, tempo) <span class="sc">%&gt;%</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">match =</span> <span class="fu">if_else</span>(playlist_genre <span class="sc">==</span> predicted_genre, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(predicted_genre)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>accuracy_predictions10 <span class="ot">&lt;-</span> predictions10 <span class="sc">%&gt;%</span> </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">match =</span> <span class="fu">ifelse</span>(playlist_genre <span class="sc">==</span> predicted_genre, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(match) <span class="sc">%&gt;%</span> </span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">accuracy =</span> n<span class="sc">/</span><span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>accuracy_predictions10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  match n accuracy
1 FALSE 8       80
2  TRUE 2       20</code></pre>
</div>
</div>
<p>Nevertheless, the rate of accuracy remained quite low at 20%.</p>
</section>
<section id="discussion-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="discussion-and-conclusion">Discussion and Conclusion</h2>
<p>In delving into the exploration of genre classification through audio features, the complexity of the task becomes apparent. The decision tree, chosen for its transparency, is a valuable tool, yet its application to genre classification reveals intricate challenges. The research question at the core of this endeavor — How Does Genre Classification Work? — is met with a nuanced response, emphasising the multifaceted nature of music genres and the inherent subjectivity in their definition.</p>
<p>Genre classification encounters complexities stemming from the diverse and evolving nature of musical styles. The decision tree, though structured with careful considerations of energy, popularity, danceability, and valence, grapples with several less quantifiable dynamic and subjective aspects inherent to genre delineation. The challenge lies not only in deciphering the intricate relationships between audio features but also in navigating the fluid boundaries between genres.</p>
<p>Furthermore, the inherent subjectivity in defining genres adds a layer of complexity. Genres are not rigidly defined categories but rather fluid and context-dependent concepts. Individual perceptions, cultural influences, and temporal shifts contribute to the malleability of genre boundaries. Consequently, a single decision tree, while illuminating certain distinctions, may struggle to encapsulate the vast spectrum of musical expression.</p>
<p>The potential interactions among audio features, not fully captured by the decision tree, pose another layer of challenge. Music is a rich tapestry where features intertwine in intricate ways, and their combined effect contributes to the holistic experience of a genre. The decision tree, by nature, compartmentalises these features, potentially overlooking synergies that play a crucial role in genre identification.</p>
<p>Addressing the research question of whether genre classification can be achieved through audio feature classification, the presented decision tree offers valuable insights but falls short of providing a definitive answer. The modest accuracy rates underscore the complexity of the task and hint at the limitations of relying solely on audio features for genre classification.</p>
<p>In conclusion, genre classification proves to be a nuanced and challenging endeavor, influenced by the multifaceted nature of musical expression, the subjectivity inherent in genre definitions, and the intricate interactions among audio features. The decision tree, while illuminating certain aspects, prompts further exploration into more sophisticated methodologies, expanded feature sets, and a deeper integration of domain knowledge.</p>
<p>As the quest for accurate genre classification continues, the intersection of technology, music theory, and human perception remains a fascinating and evolving terrain.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Goldman Sachs. (2023). <em>Music In The Air.</em> https://www.goldmansachs.com/intelligence/page/music-streaming-services-are-on-the-cusp-of-major-structural-change.html</p>
<p>Music Business Worldwide. (2023). <em>WHY GOLDMAN SACHS BELIEVES THAT SPOTIFY WILL REMAIN THE WORLD’S DOMINANT MUSIC STREAMING SERVICE IN 2030.</em> https://www.musicbusinessworldwide.com/why-goldman-sachs-believes-that-spotify-will-remain-the-worlds-dominant-music-streaming-service-in-2030/</p>
<p>Recording Industry Association of America. (2022). <em>Mid-Year 2021 RIAA Revenue Statistics.</em> https://www.riaa.com/wp-content/uploads/2021/09/Mid-Year-2021-RIAA-Music-Revenue-Report.pdf</p>
<p>The Guardian. (2017). <em>‘They could destroy the album’: how Spotify’s playlists have changed music for ever.</em> https://www.theguardian.com/music/2017/aug/17/they-could-destroy-the-album-how-spotify-playlists-have-changed-music-for-ever</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>